tables:
  # ============================================================
  # USERS — Source of Truth
  # ============================================================
  - name: project.name-environment-users
    description: User identity and profile data (source of truth)
    entity: User

    # ============================================
    # CONFIGURATION
    # ============================================
    billing_mode: PAY_PER_REQUEST
    deletion_protection: true
    point_in_time_recovery: true

    # ============================================
    # SCHEMA
    # ============================================
    attributes:
      # Primary key
      - name: userId
        type: S
        description: Primary key - UUID v4

      # Indexed attributes
      - name: email
        type: S
        description: User email (unique)

      - name: status
        type: S
        description: User status (active / suspended / pending_verification / deleted)

      - name: createdAt
        type: S
        description: ISO 8601 timestamp

      # Application-managed attributes
      - name: passwordHash
        type: S
        description: Bcrypt hash

      - name: firstName
        type: S
        description: User's first name

      - name: lastName
        type: S
        description: User's last name

      - name: phoneNumber
        type: S
        description: Optional phone number (E.164 format)

      - name: metadata
        type: M
        description: Custom key-value pairs

      - name: updatedAt
        type: S
        description: ISO 8601 timestamp

      - name: lastLoginAt
        type: S
        description: ISO 8601 timestamp (optional)

      - name: ttl
        type: N
        description: Unix timestamp for TTL expiration (soft delete)

    # ============================================
    # KEYS & INDEXES
    # ============================================
    primary_key:
      partition_key: userId
      sort_key: null

    global_secondary_indexes:
      - name: email-index
        partition_key: email
        sort_key: null
        projection_type: ALL
        description: Fast lookup by email (login, password recovery, duplicate check)

      - name: status-created-index
        partition_key: status
        sort_key: createdAt
        projection_type: INCLUDE
        projected_attributes:
          - userId
          - email
          - createdAt
        description: Lightweight queries by status (admin / operations)

    local_secondary_indexes: []

    # ============================================
    # CONSTRAINTS & GUARANTEES
    # ============================================
    constraints:
      email_uniqueness:
        description: >
          Email uniqueness is enforced at application level using a GSI lookup
          on email-index. DynamoDB does not provide native uniqueness guarantees
          on secondary indexes.
        enforcement:
          type: application_level
          mechanism:
            - Query on email-index before creation
            - Conflict handling at API level
        consistency:
          model: eventual
          notes: >
            Rare race conditions may occur under concurrent requests and are
            handled by the API returning HTTP 409 Conflict.

    # ============================================
    # FEATURES
    # ============================================
    ttl:
      enabled: true
      attribute: ttl
      description: Auto-delete soft-deleted users after retention window

    encryption:
      at_rest: AWS_MANAGED_KMS
      in_transit: TLS
      kms_key_arn: null

    streams:
      enabled: false
      view_type: null

    # ============================================
    # MONITORING
    # ============================================
    monitoring:
      cloudwatch_alarms:
        - metric: ConsumedReadCapacityUnits
          threshold: 80%
        - metric: ConsumedWriteCapacityUnits
          threshold: 80%
        - metric: UserErrors
          threshold: ">10 in 5 minutes"

    # ============================================
    # COMPLIANCE & TAGS
    # ============================================
    tags:
      DataClassification: PII
      Compliance: GDPR,SOC2
      RetentionPeriod: 7years
      CostCenter: identity-platform
      Owner: idp-team@company.com
      Domain: users
      ManagedBy: Terraform

    compliance:
      gdpr:
        - Right to deletion via soft delete + TTL
        - Data portability via list-users API
        - Encryption at rest and in transit
      soc2:
        - IAM-based access control
        - PITR enabled
        - CloudWatch monitoring

  # ============================================================
  # USER DIRECTORY — Materialized View for Listing
  # ============================================================
  - name: project.name-environment-user-directory
    description: Materialized directory for user listing and navigation
    entity: UserDirectory

    # ============================================
    # CONFIGURATION
    # ============================================
    billing_mode: PAY_PER_REQUEST
    deletion_protection: false
    point_in_time_recovery: false

    # ============================================
    # SCHEMA
    # ============================================
    attributes:
      - name: directoryShard
        type: S
        description: Shard key for horizontal partitioning (USER#00..USER#15)

      - name: createdAtUserId
        type: S
        description: createdAt#userId composite for ordering and uniqueness

      - name: userId
        type: S
        description: Reference to User.userId

      - name: email
        type: S
        description: User email (display & search)

      - name: status
        type: S
        description: User status snapshot

      - name: createdAt
        type: S
        description: User creation timestamp

    # ============================================
    # KEYS
    # ============================================
    primary_key:
      partition_key: directoryShard
      sort_key: createdAtUserId

    global_secondary_indexes: []

    local_secondary_indexes: []

    # ============================================
    # FEATURES
    # ============================================
    ttl:
      enabled: false
      description: Directory entries are derived and can be rebuilt

    encryption:
      at_rest: AWS_MANAGED_KMS
      in_transit: TLS
      kms_key_arn: null

    streams:
      enabled: false
      view_type: null

    # ============================================
    # MONITORING
    # ============================================
    monitoring:
      cloudwatch_alarms:
        - metric: ConsumedReadCapacityUnits
          threshold: 80%

    # ============================================
    # TAGS
    # ============================================
    tags:
      DataClassification: Internal
      CostCenter: identity-platform
      Owner: idp-team@company.com
      Domain: users
      ManagedBy: Terraform
